@extends('layouts.admin')
@section('title',$record['reference'] ?? 'Detail Kunjungan')
@section('content')<a class="text-link" href="{{ route('admin.records',$collection) }}">← Kembali ke daftar</a><div class="admin-detail-grid"><section class="admin-panel">
@if($collection==='applications')
@foreach(['child'=>'Data anak','parent'=>'Data orang tua / wali'] as $key=>$label)<h2>{{ $label }}</h2><dl class="detail-list">@foreach($record[$key] as $field=>$value)<dt>{{ __('fields.'.$field) }}</dt><dd>{{ $value ?: '—' }}</dd>@endforeach</dl>@endforeach
<h2>Berkas pendaftaran</h2><div class="document-links">@foreach(['birth_certificate'=>'Akta kelahiran','family_card'=>'Kartu Keluarga','photo'=>'Pas foto'] as $field=>$label)<a class="button secondary" href="{{ route('admin.document',[$record['id'],$field]) }}">↓ {{ $label }}</a>@endforeach</div>
@else<h2>Data kunjungan</h2><dl class="detail-list">@foreach(['name'=>'Nama','phone'=>'WhatsApp','email'=>'Email','date'=>'Tanggal yang diminta','notes'=>'Catatan keluarga'] as $field=>$label)<dt>{{ $label }}</dt><dd>{{ $record[$field] ?: '—' }}</dd>@endforeach</dl>@endif
<p class="record-date">Dikirim: {{ \Carbon\Carbon::parse($record['created_at'])->timezone('Asia/Jakarta')->format('d/m/Y H:i') }} WIB</p>
</section><div><form class="admin-panel" method="post" action="{{ route('admin.record.update',[$collection,$record['id']]) }}">@csrf @method('PATCH')<h2>Peninjauan</h2><label>Status<select name="status">@foreach($collection==='applications' ? ['baru','ditinjau','diterima','ditolak'] : ['baru','dikonfirmasi','selesai','dibatalkan'] as $status)<option value="{{ $status }}" @selected($record['status']===$status)>{{ ucfirst($status) }}</option>@endforeach</select></label><label>Catatan admin<textarea name="admin_notes" maxlength="5000">{{ old('admin_notes',$record['admin_notes'] ?? '') }}</textarea></label><button class="button blue">Simpan perubahan</button></form>
@if(auth()->user()->role==='owner')<form class="admin-panel danger-panel" method="post" action="{{ route('admin.record.delete',[$collection,$record['id']]) }}" data-confirm="Hapus data ini beserta semua berkasnya? Tindakan ini tidak dapat dibatalkan.">@csrf @method('DELETE')<h3>Hapus data</h3><p>Data dan berkas yang dihapus tidak dapat dikembalikan.</p><button class="button danger">Hapus permanen</button></form>@endif</div></div>@endsection
