import sys,json,re,datetime,secrets
from pathlib import Path
root=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(root/'.tools/python'))
import pymupdf
from playwright.sync_api import sync_playwright,expect

out=root/'design-audit/browser';out.mkdir(parents=True,exist_ok=True)
fixture=out/'test-document.pdf'
doc=pymupdf.open();p=doc.new_page();p.insert_text((72,72),'Dokumen uji otomatis - bukan dokumen pendaftar.');doc.save(fixture);doc.close()
credentials=(root/'storage/app/private/local-admin.txt').read_text()
email=re.search(r'Email: (.+)',credentials).group(1)
password=re.search(r'Password: (.+)',credentials).group(1)
marker='Uji Browser '+secrets.token_hex(4)
reference=None;visit_id=None;checks=[]
with sync_playwright() as p:
    browser=p.chromium.launch(executable_path='C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless=True)
    context=browser.new_context(viewport={'width':1440,'height':1000},accept_downloads=True)
    page=context.new_page();page.set_default_timeout(20000)
    page.on('dialog',lambda dialog:dialog.accept())
    page.goto('http://127.0.0.1:8000/pendaftaran/1',wait_until='networkidle')
    page.locator('[name=child_name]').fill(marker)
    page.locator('[name=nickname]').fill('Uji')
    page.locator('[name=birth_date]').fill('2019-04-10')
    page.locator('[name=gender]').select_option('Perempuan')
    page.get_by_role('button',name='Lanjutkan',exact=True).click()
    expect(page).to_have_url(re.compile('/pendaftaran/2$'))
    page.locator('[name=parent_name]').fill(marker+' Wali')
    page.locator('[name=relationship]').select_option('Ibu')
    page.locator('[name=phone]').fill('081234567890')
    page.locator('[name=email]').fill('browser-test@example.test')
    page.locator('[name=address]').fill('Alamat pengujian otomatis')
    page.get_by_role('button',name='Lanjutkan',exact=True).click()
    expect(page).to_have_url(re.compile('/pendaftaran/3$'))
    for field in ['birth_certificate','family_card']:
        page.locator(f'[name={field}]').set_input_files(str(fixture))
    page.locator('[name=photo]').set_input_files(str(root/'public/assets/design/asset-02.png'))
    page.get_by_role('button',name='Lanjutkan',exact=True).click()
    expect(page).to_have_url(re.compile('/pendaftaran/4$'))
    expect(page.locator('.review-block').first).to_contain_text(marker)
    page.screenshot(path=str(out/'registration-review.png'),full_page=True)
    page.locator('[name=consent]').check()
    page.get_by_role('button',name='Kirim Formulir',exact=True).click()
    expect(page).to_have_url(re.compile('/pendaftaran/berhasil$'))
    reference=page.locator('.registration-number strong').inner_text()
    checks.append('Four-step registration with real PDF/PNG uploads and consent passed')
    page.screenshot(path=str(out/'registration-success.png'),full_page=True)
    guest=browser.new_context()
    response=guest.request.get('http://127.0.0.1:8000/admin/berkas/'+reference+'/photo',max_redirects=0)
    assert response.status==302
    assert '/admin/login' in response.headers['location']
    response=guest.request.post('http://127.0.0.1:8000/pendaftaran/kirim',form={'consent':'1'})
    assert response.status==419
    guest.close();checks.append('Private downloads and CSRF protection passed')
    page.goto('http://127.0.0.1:8000/admin/login')
    page.locator('[name=email]').fill(email);page.locator('[name=password]').fill(password)
    page.get_by_role('button',name='Masuk',exact=True).click()
    expect(page).to_have_url(re.compile('/admin$'))
    page.goto('http://127.0.0.1:8000/admin/data/applications/'+reference)
    expect(page.locator('.detail-list').first).to_contain_text(marker)
    with page.expect_download() as download:
        page.get_by_role('link',name='↓ Akta kelahiran').click()
    assert download.value.suggested_filename=='test-document.pdf'
    page.locator('[name=status]').select_option('diterima')
    page.locator('[name=admin_notes]').fill('Pengujian otomatis; data akan dihapus.')
    page.get_by_role('button',name='Simpan perubahan',exact=True).click()
    expect(page.locator('[name=status]')).to_have_value('diterima')
    response=page.request.get('http://127.0.0.1:8000/admin/pendaftar/export')
    assert response.status==200 and reference in response.text()
    checks.append('Admin login, review, private download, status update and CSV export passed')
    page.goto('http://127.0.0.1:8000/admin/konten/home')
    page.get_by_role('button',name='Simpan konten',exact=True).click()
    expect(page.locator('[role=status]')).to_contain_text('Konten berhasil disimpan')
    checks.append('CMS save through browser passed')
    page.goto('http://127.0.0.1:8000/kontak#kunjungan')
    page.locator('[data-visit-toggle]').click()
    form=page.locator('#visit-form')
    form.locator('[name=name]').fill(marker)
    form.locator('[name=phone]').fill('081234567890')
    form.locator('[name=email]').fill('browser-test@example.test')
    day=datetime.date.today()+datetime.timedelta(days=8)
    while day.weekday()>4:day+=datetime.timedelta(days=1)
    form.locator('[name=date]').fill(day.isoformat())
    form.locator('[name=notes]').fill('Pengujian otomatis; data akan dihapus.')
    form.locator('[name=consent]').check()
    form.get_by_role('button',name='Ajukan Kunjungan').click()
    expect(page).to_have_url(re.compile('/kunjungan/berhasil$'))
    page.goto('http://127.0.0.1:8000/admin/data/visits')
    row=page.locator('tbody tr').filter(has_text=marker)
    row.get_by_role('link',name='Detail →').click()
    visit_id=page.url.rsplit('/',1)[-1]
    page.locator('[name=status]').select_option('dikonfirmasi')
    page.get_by_role('button',name='Simpan perubahan',exact=True).click()
    expect(page.locator('[name=status]')).to_have_value('dikonfirmasi')
    checks.append('Visit request and admin confirmation passed')
    page.get_by_role('button',name='Hapus permanen',exact=True).click()
    expect(page).to_have_url(re.compile('/admin/data/visits$'))
    page.goto('http://127.0.0.1:8000/admin/data/applications/'+reference)
    page.get_by_role('button',name='Hapus permanen',exact=True).click()
    expect(page).to_have_url(re.compile('/admin/data/applications$'))
    page.goto('http://127.0.0.1:8000/admin')
    page.screenshot(path=str(out/'admin-dashboard.png'),full_page=True)
    page.get_by_role('button',name='Keluar',exact=True).click()
    expect(page).to_have_url(re.compile('/admin/login$'))
    checks.append('Test records removed; logout passed')
    page.set_viewport_size({'width':768,'height':1000})
    page.goto('http://127.0.0.1:8000/')
    page.get_by_role('button',name='Buka menu').click()
    expect(page.locator('#navigation')).to_be_visible()
    page.get_by_role('link',name='Tentang Kami',exact=True).click()
    expect(page).to_have_url(re.compile('/tentang-kami$'))
    page.goto('http://127.0.0.1:8000/')
    page.locator('details summary').first.click()
    assert page.locator('details').first.get_attribute('open') is not None
    checks.append('Tablet menu and FAQ interaction passed')
    browser.close()
report={'checks':checks,'testDataCleaned':True}
(out/'workflow-report.json').write_text(json.dumps(report,indent=2),encoding='utf-8')
print(json.dumps(report,indent=2))
