@extends('layouts.site')
@section('title','Kontak — SD Ceria Nusantara')
@section('content')
<x-hero :data="$site['contact']" :contact="true"/>
<section class="section"><div class="container"><x-heading eyebrow="KONTAK SEKOLAH" title="Pilih cara yang paling nyaman" subtitle="Kami siap membantu informasi dan kunjungan keluarga."/><div class="card-grid contact-grid"><article class="info-card"><x-icon name="mail"/><h3>Email</h3><a href="mailto:{{ $site['settings']['email'] }}">{{ $site['settings']['email'] }}</a><p>Balasan pada hari kerja.</p></article><article class="info-card"><x-icon name="phone"/><h3>WhatsApp</h3><a href="https://wa.me/{{ preg_replace('/\D/','',$site['settings']['whatsapp']) }}" target="_blank" rel="noopener">{{ $site['settings']['whatsapp'] }}</a><p>{{ $site['settings']['hours'] }}</p></article><article class="info-card"><x-icon name="pin"/><h3>Alamat</h3><p>{{ $site['settings']['address'] }}</p></article></div></div></section>
<section class="section tinted"><div class="container"><x-heading eyebrow="LOKASI" title="Temukan kami di peta" subtitle="Jadwalkan kunjungan untuk mengenal lingkungan sekolah."/><a class="map-illustration" href="https://www.google.com/maps/search/?api=1&query={{ rawurlencode($site['settings']['address']) }}" target="_blank" rel="noopener" aria-label="Cari alamat sekolah di Google Maps"><x-icon name="pin"/><div><h3>{{ $site['settings']['school_name'] }}</h3><p>{{ $site['settings']['address'] }}</p></div></a></div></section>
<section class="section" id="kunjungan"><div class="container visit-panel"><x-heading eyebrow="KUNJUNGAN" title="Ingin datang dan melihat langsung?" :subtitle="'Layanan kunjungan: '.$site['contact']['visit_hours']"/>
<button class="button blue" type="button" data-visit-toggle aria-controls="visit-form" aria-expanded="{{ $errors->any() ? 'true' : 'false' }}">Jadwalkan kunjungan bersama tim sekolah</button>
<form id="visit-form" class="visit-form" action="{{ route('visit.store') }}" method="post" data-single-submit @if(!$errors->any()) hidden @endif>@csrf
@include('partials.errors')<div class="two-grid"><label>Nama orang tua / wali *<input name="name" value="{{ old('name') }}" required maxlength="120" autocomplete="name"></label><label>Nomor WhatsApp aktif *<input name="phone" value="{{ old('phone') }}" type="tel" required maxlength="25" autocomplete="tel"></label><label>Alamat email *<input name="email" value="{{ old('email') }}" type="email" required maxlength="190" autocomplete="email"></label><label>Tanggal kunjungan yang diinginkan *<input name="date" value="{{ old('date') }}" type="date" min="{{ now()->toDateString() }}" required></label><label class="full-width">Catatan<textarea name="notes" maxlength="1000">{{ old('notes') }}</textarea></label></div><label class="checkbox-label"><input type="checkbox" name="consent" value="1" required @checked(old('consent'))><span>Saya menyetujui <a class="text-link" href="{{ route('privacy') }}">kebijakan privasi</a> dan bersedia dihubungi untuk konfirmasi kunjungan.</span></label><div class="form-actions"><small>Jadwal akan dikonfirmasi kembali oleh tim sekolah.</small><button type="submit" class="button">Ajukan Kunjungan</button></div></form>
</div></section>
@endsection
