@extends('layouts.site')
@section('content')
<x-hero :data="$site['home']" :home="true"/>
<div class="school-stats"><div><strong>{{ $site['settings']['students'] }}</strong><span>Siswa aktif</span></div><div><strong>{{ $site['settings']['teachers'] }}</strong><span>Guru & staf</span></div><div><strong>{{ $site['settings']['founded'] }}</strong><span>Tahun berdiri</span></div><div><strong>{{ $site['settings']['accreditation'] }}</strong><span>Akreditasi</span></div></div>
<p class="stats-note">Mendampingi setiap anak tumbuh ceria dan percaya diri.</p>
<div class="tablet-stats container"><x-cards :items="[['title'=>$site['settings']['students'].' siswa','text'=>'Bertumbuh bersama dalam komunitas sekolah.','icon'=>'users'],['title'=>'Sejak '.$site['settings']['founded'],'text'=>$site['settings']['teachers'].' pendidik dan staf mendampingi setiap anak.','icon'=>'home']]"/></div>
<section class="home-profile section"><div class="container">
    <x-heading eyebrow="PROFIL SEKOLAH" :title="$site['home']['profile_title']" :subtitle="$site['home']['profile_subtitle']"/>
    <p class="profile-text desktop-only">{{ $site['home']['profile_text'] }}</p><p class="profile-text tablet-only">{{ $site['home']['tablet']['profile_text'] }}</p><div class="center profile-action"><a class="button blue" href="{{ route('about') }}">Kenali Sekolah Kami</a></div>
    <x-cards :items="$site['home']['values']" class="value-cards"/>
    <div class="tablet-only classroom-block"><x-heading eyebrow="KESEHARIAN" title="Belajar dengan rasa ingin tahu"/><img src="{{ $site['settings']['classroom_image'] }}" alt="Ruang belajar yang ceria" width="1672" height="941" loading="lazy"></div>
</div></section>
<section class="section tinted home-advantages"><div class="container"><x-heading eyebrow="MENGAPA MEMILIH KAMI" tablet-eyebrow="MENGAPA KAMI" title="Mendampingi setiap langkah kecil" subtitle="Keunggulan yang terasa dalam pengalaman belajar sehari-hari."/>
<div class="advantage-grid desktop-only">@foreach($site['home']['advantages'] as $item)<article class="advantage-card"><span class="number-circle">{{ str_pad($loop->iteration,2,'0',STR_PAD_LEFT) }}</span><div><h3>{{ $item['title'] }}</h3><p>{{ $item['text'] }}</p></div></article>@endforeach</div><div class="tablet-only"><x-cards :items="$site['home']['tablet']['advantages']"/></div></div></section>
<section class="section home-programs"><div class="container"><x-heading eyebrow="PROGRAM UNGGULAN" title="Belajar melalui pengalaman" subtitle="Kegiatan dirancang agar pengetahuan, kreativitas, dan karakter berkembang bersama."/>
<div class="card-grid program-cards desktop-only">@foreach($site['home']['programs'] as $item)<a class="program-card" href="{{ route('program') }}#pendekatan"><div class="program-cover color-{{ $loop->index }}"><span>{{ str_pad($loop->iteration,2,'0',STR_PAD_LEFT) }}</span></div><h3>{{ $item['title'] }}</h3><p>{{ $item['text'] }}</p><span class="text-link">Pelajari program <span aria-hidden="true">→</span></span></a>@endforeach</div><div class="tablet-only"><x-cards :items="$site['home']['tablet']['programs']"/></div></div></section>
<section class="section tinted home-facilities"><div class="container"><x-heading eyebrow="FASILITAS SEKOLAH" tablet-eyebrow="FASILITAS" title="Ruang nyaman untuk banyak kemungkinan" tablet-title="Ruang nyaman untuk tumbuh" subtitle="Setiap area mendukung anak belajar, bermain, dan mengeksplorasi."/><x-facilities :site="$site"/><p class="image-caption"><span class="desktop-only">Ruang belajar yang mendukung banyak cara untuk tumbuh.</span><span class="tablet-only">Ruang kelas, perpustakaan, lapangan olahraga, ruang seni, lab komputer, dan UKS.</span></p></div></section>
<section class="section home-teachers"><div class="container"><x-heading eyebrow="GURU & STAF" tablet-eyebrow="TIM KAMI" title="Wajah ramah di balik setiap cerita" tablet-title="Profil pendidik sekolah" subtitle="Pendidik berpengalaman dengan perhatian pada setiap anak." tablet-subtitle="Pendidik yang hadir dengan perhatian dan semangat belajar."/>
<article class="principal-card"><img src="{{ $site['teachers']['team'][0]['photo'] }}" alt="{{ $site['home']['principal_name'] }}" width="360" height="280" loading="lazy"><div><p class="eyebrow">SAMBUTAN KEPALA SEKOLAH</p><h3>“{{ $site['home']['principal_quote'] }}”</h3><p>{{ $site['home']['principal_name'] }}<br>Kepala Sekolah • Pendamping tumbuh kembang anak</p><a class="text-link" href="{{ route('teachers') }}">Lihat profil guru dan staf <span aria-hidden="true">→</span></a></div></article>
<div class="tablet-only"><x-team :site="$site"/></div></div></section>
<section class="section tinted home-testimonials"><div class="container"><x-heading eyebrow="CERITA KELUARGA" title="Kepercayaan tumbuh dari pengalaman" subtitle="Cerita orang tua tentang tumbuh bersama keluarga sekolah."/><div class="card-grid">@foreach($site['home']['testimonials'] as $item)<blockquote class="testimonial"><span aria-hidden="true">“</span><p>{{ $item['text'] }}</p><cite>{{ $item['name'] }}</cite></blockquote>@endforeach</div></div></section>
<section class="section home-admission"><div class="container"><x-heading eyebrow="ALUR PENDAFTARAN" title="Empat langkah, lebih mudah diikuti" tablet-title="Empat langkah, lebih mudah" subtitle="Informasi dan persyaratan disiapkan sebelum formulir dimulai."/><div class="admission-steps desktop-only">@foreach([['Siapkan berkas','Akta, KK, dan pas foto'],['Isi formulir','Data anak dan orang tua'],['Unggah dokumen','Periksa kelengkapan file'],['Kirim & konfirmasi','Simpan nomor pendaftaran']] as $item)<article><span>{{ $loop->iteration }}</span><h3>{{ $item[0] }}</h3><p>{{ $item[1] }}</p></article>@endforeach</div><div class="tablet-only tablet-admission"><x-cards :items="$site['home']['tablet']['admission']"/></div><div class="center"><a class="button" href="{{ route('registration',1) }}">Mulai Pendaftaran</a></div></div></section>
<section class="section tinted home-information"><div class="container"><x-heading eyebrow="INFORMASI PENDAFTARAN" title="Jelas sebelum mengambil keputusan" subtitle="Persiapkan kebutuhan anak dan jadwal kunjungan Anda."/><div class="two-grid"><article class="info-card"><h3>Jadwal & usia</h3><ul><li>Periode pendaftaran: {{ $site['settings']['period'] }}</li><li>Usia masuk: {{ $site['settings']['age'] }}</li><li>Kunjungan sekolah: berdasarkan janji</li></ul></article><article class="info-card"><h3>Berkas & biaya</h3><ul><li>Akta kelahiran, Kartu Keluarga, pas foto</li><li>Biaya pendaftaran: {{ $site['settings']['fee'] }}</li><li>Rincian resmi tersedia dalam brosur</li></ul></article></div></div></section>
<section class="section home-faq"><div class="container"><x-heading eyebrow="PERTANYAAN UMUM" title="Jawaban cepat untuk orang tua" subtitle="Topik yang paling sering ditanyakan sebelum mendaftar."/><div class="faq-grid">@foreach($site['home']['faq'] as $item)<details @if(!in_array($loop->index,[0,1,3,7])) class="desktop-only" @endif><summary>{{ $item['question'] }}<span aria-hidden="true">+</span></summary><p>{{ $item['answer'] }}</p></details>@endforeach</div></div></section>
<section class="section tinted home-register"><div class="container"><x-heading eyebrow="DAFTAR ONLINE" title="Mulai perjalanan belajar anak" subtitle="Lengkapi data anak untuk melanjutkan pendaftaran."/><form class="preview-form" method="post" action="{{ route('registration.save',1) }}">@csrf<x-steps :compact="true"/><div class="two-grid"><label>Nama lengkap anak<input name="child_name" placeholder="Isi nama lengkap anak" required maxlength="120" autocomplete="name"></label><label>Tanggal lahir<input name="birth_date" type="date" required max="{{ date('Y-m-d') }}"></label><label>Nama panggilan<input name="nickname" placeholder="Isi nama panggilan" required maxlength="60"></label><label>Jenis kelamin<select name="gender" required><option value="">Pilih jenis kelamin</option><option>Laki-laki</option><option>Perempuan</option></select></label></div><div class="form-actions"><small>Data pribadi hanya digunakan untuk proses pendaftaran.</small><button class="button">Lanjutkan</button></div></form></div></section>
@endsection
