display_errors=Off
log_errors=On
error_log=/dev/stderr
memory_limit=512M
max_execution_time=60
max_input_time=60
file_uploads=On
upload_max_filesize=1M
post_max_size=4M
upload_tmp_dir=/tmp
sys_temp_dir=/tmp
